### ISSUE TITLE
GetStarted SIP example giving 401 for Asterisk 

### ISSUE THREAD

**Issue by sourabhDemo** [sipsorcery/sipsorcery#243] opened 2020-07-07 15:47 UTC
Please consider me as beginner. I have asterisk configured on server. 
With MicroSip, I am able to connect to asterisk server with below details
- Domain: IP address(let say 10.112.122.11)
- Username: 1 (basically extension)
- Password: xxxxxxxxx
- SIP server: IP address(let say 10.112.122.11), same as domain

Now in GetStarted example, I used below details
DESTINATION = 1@10.112.122.11
At line 47, > bool callResult = await userAgent.Call(DESTINATION, Username, Password, rtpSession);

It is giving me 401: not authorized

But if I try same details in UserAgentRegister project, after second attempt it says 200 Ok.

Can you please tell me if I am missing anything

**Comment by sipsorcery** [comment] 2020-07-07 19:54
That looks like a bug (it's been there for a long time so I'm surprised this hasn't come up before). I'll fix it now but in the meantime you can work around it by using a different `SIPUserAgent.Call` method as shown below:

````csharp
SIPCallDescriptor dst = new SIPCallDescriptor(
	"username",
	"password",
	"sip:124@example.com",
	"sip:username@example.com",
	null, null, null, null,
	SIPCallDirection.Out,
	SDP.SDP_MIME_CONTENTTYPE,
	null, null
	);

// Place the call and wait for the result.
bool callResult = await userAgent.Call(dst, rtpSession);
````

**Comment by sipsorcery** [comment] 2020-07-07 21:22
This is now fixed on `master` but you'll need to use the workaround above for the current nuget package.

**Comment by sourabhDemo** [comment] 2020-07-08 08:33
Thanks for quick help. It worked. Tested with master code as well as SIPCallDescriptor way.

One query though,
My Set Up: 
- I have Asterisk server running at IP address(let say 10.112.122.11)
- Server is hosted on separate machine

Steps: I configured SIPSorcery.SoftPhone with Asterisk extension details (username, password, server and other details). Now I run the project and SoftPhone application comes up. I dial SIPSorcery.SoftPhone's extension from MicroSip (just like dialing between two MicroSip configured with two different extension of Asterisk server). 

Question 1. On click of 'Answer' button in SoftPhone, it takes time to show that user is connected in MicroSip, while in SoftPhone button changes(to Hold and Blind Transfer) quickly.
Question 2. Similarly If I click 'Hold' button in SoftPhone then it takes time to start MoH in background in MicroSIP
Question 3. Sometime when I run SoftPhone project and application comes up then i try to call from MicroSip to Softphone, it says 'service unavailable'. This happens average 3/5 times

Any suggestions if I am missing anything.

**Comment by sipsorcery** [comment] 2020-07-08 10:12
> Question 1. On click of 'Answer' button in SoftPhone, it takes time to show that user is connected in MicroSip, while in SoftPhone button changes(to Hold and Blind Transfer) quickly.

Most likely the sipsorcery softphone does the actual work of processing the answer (sending SIP response, starting RTP, getting audio devices ready etc.) asynchronously. The buttons are probably being toggled immediately without waiting for all that work to be completed.

> Question 2. Similarly If I click 'Hold' button in SoftPhone then it takes time to start MoH in background in MicroSIP

There will always be a bit of a delay but it should be less than a second. With the set up you've described the delay could be because Asterisk stays on the SIP path and when the call is put on hold it first needs to be applied to the softphone->asterisk leg and then the asterisk->microsip leg. After that the RTP media may also need to be re-invited.

A quick test would be to place a call directly between the softphone and microsip (which is how I frequently test) and see if there's any difference in the delay.

If you really want to track down the delay with the music on hold going through Asterisk you could do a Wireshark packet capture and I'd be happy to take a look.

> Question 3. Sometime when I run SoftPhone project and application comes up then i try to call from MicroSip to Softphone, it says 'service unavailable'. This happens average 3/5 times

That will be something to do with the softphone's registration with Asterisk. Probably an old registration is still current and Asterisk tries to forward to the old contact. You could put a static port in the softphone's config file so that it always listens on the same port and that should probably fix it.

**Comment by sourabhDemo** [comment] 2020-07-08 11:30
Thanks again for replying to my queries. Really appreciate !!

**Comment by sourabhDemo** [comment] 2020-07-14 03:29
I have few other queries that I am posting them here so that you have some context of my setup (from above thread). Please suggest if i need to raise a new ticket?

Short background
I have asterisk configured on server. I am successfully able to set up call via SIPSorcery to Asterisk to MicroSIP and vice versa (based on the changes you suggested)

As next step I was successfully able to set up conference using 'ASPNET.ARI - SimpleConf' example (https://github.com/skrusty/AsterNET.ARI/tree/master/Samples/SimpleConfExample). 

Q1. The SimpleConf project creates the conference but there is no extension assigned, rather it relies on conference name. How can I connect this conference from SIPSorcery (either GetStarted or SoftPhone project)?

Q2. Can I do Video call from SIPSorcery (either GetStarted or SoftPhone project) to this conference?

Please suggest if I am missing anything.

**Comment by sipsorcery** [comment] 2020-07-14 07:36
> Q1. The SimpleConf project creates the conference but there is no extension assigned, rather it relies on conference name. How can I connect this conference from SIPSorcery (either GetStarted or SoftPhone project)?

It's been a while since I've used a conference on Asterisk and I haven't used the AsterNET.ARI library so the answer is I don't know. There will most likely be a way to call into the conference via SIP but you may need to add it to your dialplan. When I did it over a decade ago it was dial into a dedicated SIP address and then enter the conference room number.

> Q2. Can I do Video call from SIPSorcery (either GetStarted or SoftPhone project) to this conference?

Again it's been a while since I look at Asterisk conferences so I don't know if video support has been added or not. The sipsorcery library can establish a Video SIP call, see the [Get Started Video example](https://github.com/sipsorcery/sipsorcery/tree/master/examples/SIPExamples/GetStartedVideo).

**Comment by sourabhDemo** [comment] 2020-07-14 07:55
Thanks for replying. 

> When I did it over a decade ago it was dial into a dedicated SIP address and then enter the conference room number.
Do you have any example in Get Started or any other material I can refer. 
Just FYI, AsterNET.ARI is an .Net library which is wrapper for AMI and AGI. This uses Web socket to connect to Asterisk and exposes API endpoint to consume in application.

> The sipsorcery library can establish a Video SIP call, see the Get Started Video example.
I tried this example with MicroSIP but it is not working. This keep on saying calling and then it ends.. no video is shared. May be i am missing something. I will check again. By any chance do have any dummy server that I can test this with?

**Comment by sipsorcery** [comment] 2020-07-14 08:36
No I don't have any Asterisk conference examples.

> I tried this example with MicroSIP but it is not working. This keep on saying calling and then it ends.. no video is shared. May be i am missing something. I will check again. By any chance do have any dummy server that I can test this with?

To make a video call with MicroSIP you need to ensure that the `VP8` codec is enabled. It's the only video codec the sipsorcery library has support for.

![microsipsettings](https://user-images.githubusercontent.com/197660/87403968-715e9d80-c5b5-11ea-852a-c8ea1a2c05ff.png)

![microsipvideo](https://user-images.githubusercontent.com/197660/87403978-74598e00-c5b5-11ea-9975-539c8722a730.png)

**Comment by sourabhDemo** [comment] 2020-07-14 09:41
Thanks for update. 
Yes I have VP8 codec checked in MicroSIP. I have both MicroSIP and SIPSorcery on Windows 10 machine(version 1809). Do I need to do some settings in OS?

Other thing, I noticed in your screenshot,  you are calling to 'thisis@anonymous.invalid' from MicroSIP. Can I call to named URI from SIPSorcery also?

**Comment by sipsorcery** [comment] 2020-07-14 09:52
The demo program sets the destination with:

`private static string DESTINATION = "aaron@127.0.0.1:6060";`

You must change that to match whatever port you have your instance of MicroSIP listening on.

![microsip_port](https://user-images.githubusercontent.com/197660/87411749-0b2b4800-c5c0-11ea-90fa-7c12478b4190.png)

**Comment by sourabhDemo** [comment] 2020-07-14 10:45
My bad, may be I am not able to put my query clearly. Thanks for being patience and responding to my beginner queries :)

Issue 1: The problem is I am able to make call between SIPSorcery - Asterisk - MicroSIP via GetStarted project. Everything works like butter. But when same configuration I put in GetStartedVideo, it shows 180 Ringing. After debugging, I found this is happening due to RTPSession. For GetStarted project, RTPSession is WindowsAudioRtpSession while in GetStartedVideo , it is RtpAVSession. 

GetStartedVideo: SDP offer
"v=0\r\no=- 1735319035 0 IN IP4 127.0.0.1\r\ns=-\r\nc=IN IP4 192.168.225.86\r\nt=0 0\r\nm=audio 62590 RTP/AVP 0 101\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-16\r\na=sendrecv\r\nm=video 62592 RTP/AVP 100\r\na=rtpmap:100 VP8/90000\r\na=sendrecv\r\n"

GetStarted: SDP offer
"v=0\r\no=- 1924662736 0 IN IP4 127.0.0.1\r\ns=-\r\nc=IN IP4 192.168.225.86\r\nt=0 0\r\nm=audio 57498 RTP/AVP 0 8 9 101\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-16\r\na=sendrecv\r\n"


Issue 2: 
With MicroSip, I am able to connect to asterisk server with below details

- Domain: IP address(let say 10.112.122.11)
- Username: 1 (basically extension)
- Password: xxxxxxxxx
- SIP server: IP address(let say 10.112.122.11), same as domain

Now in UserAgentClient example, I used below details
DESTINATION = 1@10.112.122.11

At line 139: In  SIPCallDescriptor callDescriptor = new SIPCallDescriptor(...) I have put correct details.

It is giving me 401: not authorized

**Comment by sipsorcery** [comment] 2020-07-14 11:13
The `WindowsAudioRtpSession` is broadly similar to `RtpAVSession` but without the video support. Both the SDP examples you've posted look perfectly correct. The first one includes SDP media announcements for audio AND video, the second one only has audio.

I'm very confident that the `RtpAVSession` works fine to establish a call with the MicroSIP and CounterPath Bria softphones. They are the ones I used to do all the testing in development.

Asterisk on the other hand can be a very tricky beast. I can sympathise with your frustration; I can recall the time I spent in 2004/2005 getting my first Asterisk systems configured. And Asterisk has only got more complicated since then.

I suspect your Asterisk configuration and not the sipsorcery library is your issue here. Perhaps to eliminate one of your moving parts you should try and set up a video call with two instances of MicroSIP and Asterisk.

**Comment by sourabhDemo** [comment] 2020-07-17 03:11
Sorry for being late, have been stuck in some other work. Yes, I checked RTVSession is working. But I guess problem is with running GetStartedVideo on Windows 10, in that it does not work. 
On ubuntu, GetStartedVideo works fine. But when I try calling back with Video, below is the error I got

> [21:06:10 DBG] Set remote video track SSRC to 1221045292.
> [21:06:11 ERR] Exception UdpReceiver.EndReceiveMessage. System.MissingMethodException: Method not found: 'System.String SIPSorcery.Sys.TypeExtensions.HexStr(Byte[], Int32)'.
>    at SIPSorcery.Media.RtpAVSession.RenderVideo(RTPPacket rtpPacket)
>    at SIPSorcery.Net.RTPSession.OnReceive(Int32 localPort, IPEndPoint remoteEndPoint, Byte[] buffer) in C:\Users\root\Ubuntu\sipsorcery-master\src\net\RTP\RTPSession.cs:line 2092
>    at SIPSorcery.Net.RTPChannel.OnRTPPacketReceived(UdpReceiver receiver, Int32 localPort, IPEndPoint remoteEndPoint, Byte[] packet) in C:\Users\root\Ubuntu\sipsorcery-master\src\net\RTP\RTPChannel.cs:line 446
>    at SIPSorcery.Net.UdpReceiver.EndReceiveFrom(IAsyncResult ar) in C:\Users\root\Ubuntu\sipsorcery-master\src\net\RTP\RTPChannel.cs:line 120
> [21:06:11 DBG] RTPChannel closing, RTP receiver on port 50616, Control receiver on port 50617. Reason: Method not found: 'System.String SIPSorcery.Sys.TypeExtensions.HexStr(Byte[], Int32)'..
> [21:06:11 DBG] RTPChannel closing, RTP receiver on port 50614, Control receiver on port 50615. Reason: Method not found: 'System.String SIPSorcery.Sys.TypeExtensions.HexStr(Byte[], Int32)'..

Any suggestion if I am missing something.

**Comment by sipsorcery** [comment] 2020-07-17 09:11
> On ubuntu, GetStartedVideo works fine.

It definitely doesn't. That example requires Windows Forms which isn't available on non-Windows platforms.

Using audio/video devices (which is what `RtpAVSession's` purpose) is only supported on Windows. Note:

> **This library does not provide any interface for audio/video capturing/rendering. For Windows the companion SIPSorceryMedia library does provide some audio & video functions. Supporting cross platform audio/video with .NET Core is a major project by itself.**

**Comment by sourabhDemo** [comment] 2020-07-17 09:32
Sorry I forgot to update. My bad :( it was not ubuntu, but Windows 10. Actually it was on other Windows 10 machine where GetStartedVideo works fine, but not on my windows 10 machine. This is internal issue to me. I figured out after my post.

Just any suggestion on error. I can see this method exist but still getting error when I try calling back with Video

> [21:06:10 DBG] Set remote video track SSRC to 1221045292.
> [21:06:11 ERR] Exception UdpReceiver.EndReceiveMessage. System.MissingMethodException: Method not found: 'System.String SIPSorcery.Sys.TypeExtensions.HexStr(Byte[], Int32)'.
> at SIPSorcery.Media.RtpAVSession.RenderVideo(RTPPacket rtpPacket)
> at SIPSorcery.Net.RTPSession.OnReceive(Int32 localPort, IPEndPoint remoteEndPoint, Byte[] buffer) in C:\Users\root\Ubuntu\sipsorcery-master\src\net\RTP\RTPSession.cs:line 2092
> at SIPSorcery.Net.RTPChannel.OnRTPPacketReceived(UdpReceiver receiver, Int32 localPort, IPEndPoint remoteEndPoint, Byte[] packet) in C:\Users\root\Ubuntu\sipsorcery-master\src\net\RTP\RTPChannel.cs:line 446
> at SIPSorcery.Net.UdpReceiver.EndReceiveFrom(IAsyncResult ar) in C:\Users\root\Ubuntu\sipsorcery-master\src\net\RTP\RTPChannel.cs:line 120
> [21:06:11 DBG] RTPChannel closing, RTP receiver on port 50616, Control receiver on port 50617. Reason: Method not found: 'System.String SIPSorcery.Sys.TypeExtensions.HexStr(Byte[], Int32)'..
> [21:06:11 DBG] RTPChannel closing, RTP receiver on port 50614, Control receiver on port 50615. Reason: Method not found: 'System.String SIPSorcery.Sys.TypeExtensions.HexStr(Byte[], Int32)'..

**Comment by sipsorcery** [comment] 2020-07-17 09:45
Are you building the main sipsorcery library from source?

The problem is the `SIPSorceryMedia` dll depends on `SIPSorcery.dll` so the versions have to match. If you attempt to use a custom build of sipsorcery AND also reference `SIPSorceryMedia` problems like the one above can occur.

It's not a great situation and I'd like to replace `SIPSorceryMedia` with `PInvoke` calls but it's a big job. In the meantime the only other option is to build `SIPSorceryMedia` as the same time as `SIPSorcery`. That requires a bit of set up and C++ know how.

I plan on releasing a new nuget package early next week. You might be better off waiting for that if you don't want to try the above.

**Comment by sourabhDemo** [comment] 2020-07-17 09:50
Thanks for replying. I am really thankful and appreciate your help 🥇

**Closed** 2020-07-20 11:42 UTC
Labels: bug, question
